using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
//      Access Modifiers 
//--> C sharp provide you with access modifiers that allow yuu to specify which classes can the datamembers of a particular class.
//--> in c sharp there are four commounly used acces modifiers 
//--> 1. Public  2. Private   3. Protected 4. Internal
// --> in c sharp deault access modifier for top-level class and structs is internal,while the
// default access modifier for class members (fieldsm methdos, properties, etc ) is private.
// Additionally m nested type within a class or struct also default to private.

//                RULES FOR ACCESS MODIFIERS
//--> Members of same class can access each other.
//--> Only Public and internal access modifiers are used with the class.

//               ACCESS MODIFIERS
//--> Public - the public access modifier provies the most permissive access level.
//-->        - the members declared as public can be accessed anywhere in the class as well as from other classes.
//-->Private - The private access modifier provides the least permissive access level
//           - Private members are accessible only within the class in which they are declared.
//           
//--> Protected -the protected access modifier allows the class members to be accessible within the class as well as within the derived classes.
//--> Internal - the internal access modifier allows the class members to be accessible only within the clasees of the same namespace /assembly.
//             - an assembly is a file that is automatically generated by the compiler upon successful compilation of a .Net application.
//             - the code declares a variable called NumOne as internal, which means it has only assembly-level access.


namespace Learning_C_Sharp
{
    internal class complie_time_overloading_method
    {
        static void Main(string[] args)
        {


            Console.ReadLine();
        }
    }
}
